# Generated by Django 6.0 on 2026-01-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('Peut_supprimer_article', 'peut supprimer article'), ('Peut_modifier_article', 'peut modifier article')]},
        ),
    ]
